version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
    groups:
      payloadcms:
        patterns:
          - 'payload'
          - '@payloadcms/*'
    allow:
      - dependency-name: 'payload'
      - dependency-name: '@payloadcms/*'
